#!/usr/bin/env bash
# fetch_demo.sh — 可复现地获取官方 MiniCPM-o-Demo 前端
# 固定 commit，HTTPS shallow clone，blobless filter。验证 SHA，记录元数据。
set -Eeuo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

DEMO_REPO="https://github.com/OpenBMB/MiniCPM-o-Demo.git"
DEMO_COMMIT="ba7fa9cc6ad63c894f1bd5e5afac28466953519d"
DEMO_DIR="${REPO_ROOT}/third_party/MiniCPM-o-Demo"
DEMO_META="${REPO_ROOT}/submission/demo/demo_metadata.env"
TIMEOUT_S="${FETCH_DEMO_TIMEOUT:-300}"

echo "=== fetch_demo: MiniCPM-o-Demo ==="
echo "  REPOSITORY  = ${DEMO_REPO}"
echo "  COMMIT      = ${DEMO_COMMIT}"
echo "  TARGET      = ${DEMO_DIR}"
echo "  METHOD      = HTTPS_SHALLOW_CLONE (depth=1, filter=blob:none)"

# Already at correct commit?
if [ -d "${DEMO_DIR}/.git" ]; then
  CURRENT="$(cd "${DEMO_DIR}" && git rev-parse HEAD 2>/dev/null || echo '')"
  if [ "${CURRENT}" = "${DEMO_COMMIT}" ]; then
    echo "  STATUS      = ALREADY_PINNED (${CURRENT:0:7})"
    exit 0
  else
    echo "  STATUS      = WRONG_COMMIT (${CURRENT:-none}, expected ${DEMO_COMMIT:0:7})"
    echo "  请删除 ${DEMO_DIR} 后重试: rm -rf ${DEMO_DIR} && bash $0"
    exit 2
  fi
fi

# Clone
echo "  正在 clone..."
mkdir -p "$(dirname "${DEMO_DIR}")"
timeout "${TIMEOUT_S}" git \
  -c http.version=HTTP/1.1 \
  clone \
  --depth 1 \
  --filter=blob:none \
  "${DEMO_REPO}" \
  "${DEMO_DIR}"

# Verify
ACTUAL="$(cd "${DEMO_DIR}" && git rev-parse HEAD)"
if [ "${ACTUAL}" != "${DEMO_COMMIT}" ]; then
  echo "  [FAIL] commit 不匹配: expected ${DEMO_COMMIT}, got ${ACTUAL}"
  exit 3
fi

echo "  VERIFIED    = ${ACTUAL:0:7}"
echo "  FILES       = $(cd "${DEMO_DIR}" && git ls-files | wc -l)"

# Write metadata
cat > "${DEMO_META}" <<EOF
# Demo metadata — generated by fetch_demo.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)
DEMO_REPOSITORY=${DEMO_REPO}
DEMO_COMMIT=${DEMO_COMMIT}
DEMO_FETCH_METHOD=HTTPS_SHALLOW_CLONE
DEMO_FETCH_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
DEMO_DIR=${DEMO_DIR}
EOF

echo "  META        = ${DEMO_META}"
echo "=== fetch_demo: DONE ==="
