#!/usr/bin/env python3
"""DSpark on-device fine-tune on torch-npu (Ascend 910C).

Kills train/inference mismatch at the root: trains the draft on rollout data
generated by the actual C++/NPU inference stack (rollout_dump), replicating
the exact dflash graph semantics:
  encoder:  h = RMSNorm(fc(F))                       F=[n,20480] target layer-inputs
  inject:   K = rope(k_norm(wk(h))), V = wv(h)       (draft KV from target features)
  decode:   x = tok_embd[tokens] -> 5 qwen3 layers (attn over injected KV, causal)
            -> output_norm -> lm_head (target's, frozen)
Loss: dtriad approximation = 0.1*CE(draft_logits, target_greedy) + 0.9*L1(draft_hid, target_hid)
      (confidence/markov heads frozen - production runs p_min=0)
Usage: python3 train_ascend.py --data /tmp/dspark_train_data --epochs 4 --lr 2e-6
"""
import argparse, glob, os, struct, sys
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from safetensors import safe_open

D, NHL, HKV, HD, FF = 4096, 32, 8, 128, 12288
EPS, ROPE_BASE, NL = 1e-6, 1e6, 5
ROPE_NORM = os.environ.get('ROPE_MODE', 'norm') == 'norm'  # 'norm'=interleaved, 'neox'=half-split

# ---------------- weights ----------------
def load_draft(path):
    ws = {}
    with safe_open(path, framework='pt') as sf:
        for k in sf.keys():
            ws[k] = sf.get_tensor(k).float()
    return ws

def read_gguf(path, names):
    sys.path.insert(0, '/workspace/llama-cpp-upstream-dspark/gguf-py')
    import gguf
    r = gguf.GGUFReader(path)
    tmap = {t.name: t for t in r.tensors}
    out = {}
    for n in names:
        t = tmap[n]
        arr = np.array(t.data)  # handles f16/f32/bf16 via dtype
        out[n] = torch.from_numpy(arr.astype(np.float32))
    return out

# ---------------- modules ----------------
class RMS(nn.Module):
    def __init__(self, w):
        super().__init__()
        self.w = nn.Parameter(w)
    def forward(self, x):
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + EPS) * self.w

def rope_cos_sin(pos, dim, base, dtype, device):
    # pos [n], dim=128
    inv = base ** (-torch.arange(0, dim, 2, dtype=torch.float32, device=device) / dim)  # [d/2]
    t = pos.float()[:, None] * inv[None, :]                                             # [n, d/2]
    return t.cos().to(dtype), t.sin().to(dtype)

def apply_rope(x, cos, sin):
    # x [..., n, head, 128] -> rotate. norm-mode: pairs (2i,2i+1); neox: halves
    if ROPE_NORM:
        x1, x2 = x[..., 0::2], x[..., 1::2]
        c = cos[:, None, :]  # [n,1,64] broadcast over heads
        s = sin[:, None, :]
        r1 = x1 * c - x2 * s
        r2 = x1 * s + x2 * c
        out = torch.stack((r1, r2), dim=-1).flatten(-2)
        return out
    else:
        half = x.shape[-1] // 2
        x1, x2 = x[..., :half], x[..., half:]
        c = cos[:, None, :]
        s = sin[:, None, :]
        return torch.cat((x1 * c - x2 * s, x1 * s + x2 * c), dim=-1)

class Layer(nn.Module):
    def __init__(self, ws, i):
        super().__init__()
        p = f'layers.{i}.'
        self.attn_norm = RMS(ws[p + 'input_layernorm.weight'])
        self.qn = RMS(ws[p + 'self_attn.q_norm.weight'])
        self.kn = RMS(ws[p + 'self_attn.k_norm.weight'])
        self.wq = nn.Parameter(ws[p + 'self_attn.q_proj.weight'])
        self.wk = nn.Parameter(ws[p + 'self_attn.k_proj.weight'])
        self.wv = nn.Parameter(ws[p + 'self_attn.v_proj.weight'])
        self.wo = nn.Parameter(ws[p + 'self_attn.o_proj.weight'])
        self.ffn_norm = RMS(ws[p + 'post_attention_layernorm.weight'])
        self.wg = nn.Parameter(ws[p + 'mlp.gate_proj.weight'])
        self.wu = nn.Parameter(ws[p + 'mlp.up_proj.weight'])
        self.wd = nn.Parameter(ws[p + 'mlp.down_proj.weight'])

    def forward(self, x, K_inj, V_inj, cos, sin, n_ctx):
        # x [n,4096]; K_inj [n,KV,128] (already normed+roped), V_inj [n,KV,128]
        h = self.attn_norm(x)
        q = (h @ self.wq.T).view(-1, NHL, HD)
        k = (h @ self.wk.T).view(-1, HKV, HD)
        v = (h @ self.wv.T).view(-1, HKV, HD)
        q = apply_rope(self.qn(q), cos, sin)
        k = apply_rope(self.kn(k), cos, sin)
        # attention over injected KV only (full-injection teacher forcing)
        rep = NHL // HKV
        Kg = K_inj.repeat_interleave(rep, dim=1)   # [n,32,128] kv head = h//rep
        Vg = V_inj.repeat_interleave(rep, dim=1)
        att = torch.einsum('qhd,khd->hqk', q.float(), Kg.float()) / (HD ** 0.5)
        mask = torch.triu(torch.ones(n_ctx, n_ctx, device=q.device, dtype=torch.bool), 1)
        att = att.masked_fill(mask, float('-inf')).softmax(-1)
        o = torch.einsum('hqk,khd->qhd', att.to(Vg.dtype), Vg)
        x = x + (o.reshape(-1, NHL * HD) @ self.wo.T)
        h2 = self.ffn_norm(x)
        ff = (F.silu(h2 @ self.wg.T) * (h2 @ self.wu.T)) @ self.wd.T
        return x + ff

class Draft(nn.Module):
    def __init__(self, ws, tok_embd, lm_head):
        super().__init__()
        self.fc = nn.Parameter(ws['fc.weight'])
        self.enc_norm = RMS(ws['hidden_norm.weight'])
        self.layers = nn.ModuleList([Layer(ws, i) for i in range(NL)])
        self.out_norm = RMS(ws['norm.weight'])
        self.register_buffer('tok_embd', tok_embd)   # [vocab, 4096] frozen
        self.register_buffer('lm_head', lm_head.T.contiguous())  # [4096, vocab] frozen
        for b in ('tok_embd', 'lm_head'):
            getattr(self, b).requires_grad_(False)

    def forward(self, Ffeat, tokens, pos):
        # Ffeat [n,20480] f32, tokens [n], pos [n]
        n = Ffeat.shape[0]
        h = self.enc_norm(Ffeat @ self.fc.T)                    # [n,4096]
        cos, sin = rope_cos_sin(pos, HD, ROPE_BASE, h.dtype, h.device)
        x = self.tok_embd[tokens]
        for li, layer in enumerate(self.layers):
            ki = (h @ layer.wk.T).view(-1, HKV, HD)
            ki = apply_rope(layer.kn(ki), cos, sin)             # injected K
            vi = (h @ layer.wv.T).view(-1, HKV, HD)             # injected V
            x = layer(x, ki, vi, cos, sin, n)
        hid = self.out_norm(x)
        logits = hid @ self.lm_head
        return logits, hid

# ---------------- data ----------------
def load_shards(data_dir, max_prefill_pos=2048):
    seqs = []
    for fe in sorted(glob.glob(os.path.join(data_dir, '*_feat.f32'))):
        pfx = fe[:-len('_feat.f32')]
        try:
            feat = np.fromfile(fe, np.float32).reshape(-1, 20480)
            hid = np.fromfile(pfx + '_hid.f32', np.float32).reshape(-1, 4096)
            tok = np.fromfile(pfx + '_in.i32', np.int32)
            lab = np.fromfile(pfx + '_lab.i32', np.int32)
            meta = dict(kv.split('=', 1) for kv in open(pfx + '_meta.txt').read().strip().split(' ') if '=' in kv)
            pf = int(meta['prefill_n'])
        except Exception:
            continue
        n = min(len(tok), len(lab), feat.shape[0], hid.shape[0])
        if n < 2:
            continue
        pos = np.arange(pf - 1, pf - 1 + n, dtype=np.int64)
        # trim degenerate tails: window of 8 where one label repeats >=6 times
        # (echo loops / listen-spam / newline runs) — keep the prefix before it
        for i in range(n - 8):
            w = lab[i:i + 8]
            if np.bincount(w, minlength=1).max(initial=0) >= 6:
                n = i
                break
        if n < 2:
            continue
        seqs.append(dict(feat=feat[:n], hid=hid[:n], tok=tok[:n], lab=lab[:n], pos=pos[:n]))
    return seqs

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data', default='/tmp/dspark_train_data')
    ap.add_argument('--ckpt', default='/workspace/models/dspark-stage10/model.safetensors')
    ap.add_argument('--target', default='/workspace/shared_assets/models/OpenBMB/MiniCPM-o-4_5-gguf/MiniCPM-o-4_5-F16.gguf')
    ap.add_argument('--epochs', type=int, default=4)
    ap.add_argument('--lr', type=float, default=2e-6)
    ap.add_argument('--ce', type=float, default=0.1)
    ap.add_argument('--l1', type=float, default=0.9)
    ap.add_argument('--out', default='/workspace/models/dspark-stage10/model_ascend_ft.safetensors')
    ap.add_argument('--eval-only', action='store_true')
    args = ap.parse_args()

    dev = torch.device('npu:0')
    torch.npu.set_device(0)

    ws = load_draft(args.ckpt)
    shared = read_gguf(args.target, ['token_embd.weight', 'output.weight'])
    model = Draft(ws, shared['token_embd.weight'], shared['output.weight']).to(dev).to(torch.float32)

    seqs = load_shards(args.data)
    tot = sum(len(s['lab']) for s in seqs)
    print(f'{len(seqs)} shards, {tot} rows')

    # ---- teacher-forced accuracy BEFORE training (sanity: must be ~C++ acceptance 16-50%)
    model.eval()
    with torch.no_grad():
        hit = cnt = 0
        for s in seqs[:8]:
            feat = torch.from_numpy(s['feat']).to(dev)
            toks = torch.from_numpy(s['tok']).to(dev)
            pos = torch.from_numpy(s['pos']).to(dev)
            logits, _ = model(feat, toks, pos)
            pred = logits.argmax(-1).cpu().numpy()
            hit += int((pred == s['lab']).sum())
            cnt += len(s['lab'])
        print(f'[eval-pre] teacher-forced next-token acc = {hit/cnt:.4f} ({hit}/{cnt})')

    if args.eval_only:
        return

    # ---- train (bf16 autocast on NPU) ----
    trainable = [p for p in model.parameters() if p.requires_grad]
    opt = torch.optim.AdamW(trainable, lr=args.lr, weight_decay=0.0)
    model.train()
    step = 0
    for ep in range(args.epochs):
        order = np.random.default_rng(ep).permutation(len(seqs))
        tot_loss = 0.0
        for si in order:
            s = seqs[si]
            feat = torch.from_numpy(s['feat']).to(dev)
            hid_t = torch.from_numpy(s['hid']).to(dev)
            toks = torch.from_numpy(s['tok']).to(dev)
            labs = torch.from_numpy(s['lab']).to(dev).long()
            pos = torch.from_numpy(s['pos']).to(dev)
            with torch.autocast('npu', dtype=torch.bfloat16):
                logits, hid = model(feat, toks, pos)
                ce = F.cross_entropy(logits.float(), labs)
                l1 = F.l1_loss(hid.float(), hid_t.float())
                loss = args.ce * ce + args.l1 * l1
            opt.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(trainable, 1.0)
            opt.step()
            tot_loss += loss.item()
            step += 1
        print(f'epoch {ep}: mean loss {tot_loss/max(1,len(seqs)):.4f} (steps={step})')

    # ---- post-train accuracy ----
    model.eval()
    with torch.no_grad():
        hit = cnt = 0
        for s in seqs[:8]:
            feat = torch.from_numpy(s['feat']).to(dev)
            toks = torch.from_numpy(s['tok']).to(dev)
            pos = torch.from_numpy(s['pos']).to(dev)
            logits, _ = model(feat, toks, pos)
            pred = logits.argmax(-1).cpu().numpy()
            hit += int((pred == s['lab']).sum())
            cnt += len(s['lab'])
        print(f'[eval-post] teacher-forced next-token acc = {hit/cnt:.4f} ({hit}/{cnt})')

    # ---- export f32 safetensors in the ORIGINAL layout ----
    from safetensors.torch import save_file
    out_ws = {}
    out_ws['fc.weight'] = model.fc.detach().cpu()
    out_ws['hidden_norm.weight'] = model.enc_norm.w.detach().cpu()
    out_ws['norm.weight'] = model.out_norm.w.detach().cpu()
    with safe_open(args.ckpt, framework='pt') as sf:
        for k in ('confidence_head.proj.weight', 'confidence_head.proj.bias',
                  'markov_head.markov_w1.weight', 'markov_head.markov_w2.weight'):
            out_ws[k] = sf.get_tensor(k)
    for i, layer in enumerate(model.layers):
        p = f'layers.{i}.'
        out_ws[p + 'input_layernorm.weight'] = layer.attn_norm.w.detach().cpu()
        out_ws[p + 'post_attention_layernorm.weight'] = layer.ffn_norm.w.detach().cpu()
        out_ws[p + 'self_attn.q_norm.weight'] = layer.qn.w.detach().cpu()
        out_ws[p + 'self_attn.k_norm.weight'] = layer.kn.w.detach().cpu()
        out_ws[p + 'self_attn.q_proj.weight'] = layer.wq.detach().cpu()
        out_ws[p + 'self_attn.k_proj.weight'] = layer.wk.detach().cpu()
        out_ws[p + 'self_attn.v_proj.weight'] = layer.wv.detach().cpu()
        out_ws[p + 'self_attn.o_proj.weight'] = layer.wo.detach().cpu()
        out_ws[p + 'mlp.gate_proj.weight'] = layer.wg.detach().cpu()
        out_ws[p + 'mlp.up_proj.weight'] = layer.wu.detach().cpu()
        out_ws[p + 'mlp.down_proj.weight'] = layer.wd.detach().cpu()
    save_file({k: v.contiguous() for k, v in out_ws.items()}, args.out)
    print('saved ->', args.out)

if __name__ == '__main__':
    main()
